### ISSUE TITLE
build myself

### ISSUE THREAD

**Issue by snahmad** [kiyolee/libzip-win-build#1]
Hi,
How can i build myself. It depends on zlib. where to put zli?

**Comment by kiyolee** [comment]
Just clone my zlib-win-build repository. Put it along side each other, i.e. both libzip and zlib share the same parent directory.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by snahmad** [comment]
send me your zip contains all source including libzip and zlib.

**Comment by kiyolee** [comment]
Just download the released source zip file from github then. Check my zlib-win-build repository there.

Get Outlook for Android<https://aka.ms/ghei36>
