### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by nurbles** [kiyolee/libzip-win-build#10]
I'm trying to back-port a 64 bit program I built with VS2022 so that a customer still running our 10+ year old 32-bit Win7 code can use it.  I've stripped everything out except creating the zip file, but when the program calls zip_open() it gets an ILLEGAL INSTRUCTION exception that has the debugger pointing at line 87 in zip_source_file_common.c.  Here's a snippet:
```
   if (len < 0) {
      if( len == -1) {
         len = ZIP_LENGTH_TO_END;   // <== highlighted statement in debugger
      }
      // TODO: return ZIP_ER_INVAL if len != ZIP_LENGHT_UNCHECKED?
      length = 0;
   }
```
The exception 0xC000001D occurred at 0x5293a19c.  Here's what the debugger shows for the disassembly around the exception:
```
    if (len < 0) {
5293A183  cmp         dword ptr [ebp+1Ch],0  
5293A187  jg          zip_source_file_common_new+140h (5293A1B0h)  
5293A189  jl          zip_source_file_common_new+121h (5293A191h)  
5293A18B  cmp         dword ptr [ebp+18h],0  
5293A18F  jae         zip_source_file_common_new+140h (5293A1B0h)  
        if (len == -1) {
5293A191  mov         edx,dword ptr [ebp+18h]  
5293A194  and         edx,dword ptr [ebp+1Ch]  
5293A197  cmp         edx,0FFFFFFFFh  
5293A19A  jne         zip_source_file_common_new+135h (5293A1A5h)  
            len = ZIP_LENGTH_TO_END;
5293A19C  vxorpd      xmm0,xmm0,xmm0  
5293A1A0  vmovlpd     qword ptr [ebp+18h],xmm0  
        }
        // TODO: return ZIP_ER_INVAL if len != ZIP_LENGTH_UNCHECKED?
        length = 0;
5293A1A5  vxorpd      xmm0,xmm0,xmm0  
5293A1A9  vmovlpd     qword ptr [ebp-34h],xmm0  
    }
```
I have tried the release and debug of both the static and DLL versions of the libraries as well as with the original build settings and with all optimization disabled (sometimes VS2010's optimizer generated less than good code.)  Unfortunately, I get the same error no matter what.

FWIW, all of this code works perfectly with VS2022 and the libzip built with vcpkg.  But, I must use VS2010, and vcpkg doesn't work with VS2010.  Unfortunately, neither are the VS2010 projects files I got here ... or perhaps the libzip/zlib sources or just VS2010 itself.

If there is any way to get this to work, it would be greatly appreciated.  If not, then we'll need to tell the customer they can't use the new tool until after they upgrade to Windows 11.

**Comment by kiyolee** [comment]
I have enabled AVX by default, that may not work with CPU too old.

**Comment by kiyolee** [comment]
You may clone the repo, revert this commit https://github.com/kiyolee/libzip-win-build/commit/26072bfe899638928add9b89538b93e151e65d56 and try.

**Comment by nurbles** [comment]
Thanks!  That was exactly what I needed!  I searched through the project options within VS2010 for AVX, too, but I somehow missed the option -- wherever it was hidden.  Removing those four lines from the .props file got everything working great!

Thanks again!  You're the greatest!  (smile)
