### ISSUE TITLE
Need a build support for ARM64

### ISSUE THREAD

**Issue by PratyakshSinha** [kiyolee/libzip-win-build#11]
Solution for arm64 arch exists for libz and it builds fine as well with it, similarly support for ARM64 is needed for libzip as well.

**Comment by kiyolee** [comment]
I am happy to add that support.
Please just wait.

**Comment by kiyolee** [comment]
Done. Check latest release.

**Comment by PratyakshSinha** [comment]
@kiyolee It is building and working fine now thank you very much for the support.
