### ISSUE TITLE
Last release of libzip build failed.

### ISSUE THREAD

**Issue by ValentiWorkLearning** [kiyolee/libzip-win-build#3]
It's not your problem, but last release of libzip has failed. Since commit  d68a667302d1251c49d
 libzip's CI can't build the library.

**Comment by kiyolee** [comment]
The commit you quoted is for cmake and has nothing to do with my offering here.
Are you reporting problem to the wrong place?

**Comment by kiyolee** [comment]
Irrelevant report.
