### ISSUE TITLE
Update libzip

### ISSUE THREAD

**Issue by DLL125** [kiyolee/libzip-win-build#7]
Hi, 

There is a new version of libzip (1.10.0). Could you update this repo? :)

**Comment by kiyolee** [comment]
Thanks for the reminder. But I am on holiday for next 2 weeks. I will get to it when I am back home.

**Comment by DLL125** [comment]
> Thanks for the reminder. But I am on holiday for next 2 weeks. I will get to it when I am back home.

Enjoy your holiday, mate!

**Comment by kiyolee** [comment]
Updated to 1.10.0 now.
