### ISSUE TITLE
Build using OpenSSL instead of Microsoft Windows Cryptography Framework?

### ISSUE THREAD

**Issue by RCECoder** [kiyolee/libzip-win-build#9]
I have OpenSSL 3.1.4
I see there is no equivalent of `_zip_crypto_hmac` function in `zip_crypto_openssl.c` file. It only refers to `zip_crypto_win.c`  which uses Microsoft Windows Cryptography Framework.

The same is true for `_zip_crypto_pbkdf2`.

Is something missing here?

**Comment by kiyolee** [comment]
My OpenSSL projects/solutions are intentionally stuck to default configuration. It is impossible to support all the varying combinations of configuration for OpenSSL. Whoever needs custom configuration should build with official methods.
Your change to config.h may work only for the purpose of building what you need.
Unit testing, for instance, may need other changes to follow.
However, HAVE_WINDOWS_CRYPTO may be a good option to be enabled on top of default. We are talking about Windows build anyway. I'd think about that.
